# Generated by Django 5.2.5 on 2026-01-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbank',
            name='bank_type',
            field=models.CharField(choices=[('COMMERCIAL', 'Commercial Bank'), ('ISLAMIC', 'Islamic Bank'), ('MICROFINANCE', 'Microfinance Bank'), ('ELECTRONIC_WALLET', 'Electronic Wallet Provider')], default='COMMERCIAL', max_length=30),
        ),
        migrations.AddField(
            model_name='commercialbank',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='commercialbank',
            name='license_status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Licensed'), ('PENDING', 'Pending Approval'), ('EXPIRED', 'Expired'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='commercialbank',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
