# Generated by Django 5.2.5 on 2026-01-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_bank', '0002_commercialbank_bank_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان التعميم')),
                ('content', models.TextField(verbose_name='نص التعميم')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='circulars/', verbose_name='المرفقات')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='عاجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
            ],
            options={
                'verbose_name': 'تعميم',
                'verbose_name_plural': 'التعاميم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='commercialbank',
            name='bank_type',
            field=models.CharField(choices=[('COMMERCIAL', 'بنك تجاري'), ('ISLAMIC', 'بنك إسلامي'), ('MICROFINANCE', 'بنك تمويل أصغر'), ('ELECTRONIC_WALLET', 'مزود محفظة إلكترونية')], default='COMMERCIAL', max_length=30),
        ),
        migrations.AlterField(
            model_name='commercialbank',
            name='license_status',
            field=models.CharField(choices=[('ACTIVE', 'نشط / مرخص'), ('PENDING', 'قيد الاختبار / بانتظار الموافقة'), ('EXPIRED', 'منتهي الصلاحية'), ('SUSPENDED', 'موقوف مؤقتاً')], default='ACTIVE', max_length=20),
        ),
    ]
