# Generated by Django 5.2.5 on 2026-01-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_bank', '0003_circular_alter_commercialbank_bank_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbank',
            name='wallet_product_name',
            field=models.CharField(default='المحفظة الإلكترونية', max_length=100, verbose_name='اسم منتج المحفظة'),
        ),
    ]
