# Generated by Django 5.2.5 on 2026-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_bank', '0004_commercialbank_wallet_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbank',
            name='currency',
            field=models.CharField(default='YER', max_length=10, verbose_name='العملة الرسمية'),
        ),
    ]
