# Generated by Django 5.2.5 on 2025-12-10 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'البطاقة الشخصية'), ('HIGH_SCHOOL_CERT', 'شهادة الثانوية العامة'), ('PHOTO', 'صورة شخصية'), ('BIRTH_CERT', 'شهادة الميلاد'), ('OTHER', 'أخرى')], max_length=20)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='student.studentprofile')),
            ],
        ),
    ]
