# Generated by Django 5.2.5 on 2025-12-18 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_studentprofile_high_school_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='high_school_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tawjihi Score', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
