# Generated by Django 5.2.5 on 2025-12-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentprofile_high_school_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.CharField(blank=True, choices=[('HS_SCORE_LOW', 'معدل الثانوية أقل من الحد الأدنى'), ('DOCS_INCOMPLETE', 'الوثائق المطلوبة غير مكتملة'), ('SEATS_FULL', 'عدم توفر مقاعد شاغرة'), ('DATA_MISMATCH', 'عدم تطابق البيانات المدخلة'), ('OTHER', 'أسباب أخرى')], max_length=50, null=True),
        ),
    ]
