# Generated by Django 5.2.5 on 2026-02-23 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_application_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('HS_CERT', 'شهادة الثانوية العامة'), ('ID_CARD', 'بطاقة الهوية'), ('PASSPORT', 'جواز السفر'), ('OTHER', 'أخرى')], max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='student.studentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
