# Generated by Django 5.2.5 on 2026-02-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_alter_document_document_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='seat_number',
            field=models.CharField(blank=True, help_text='رقم الجلوس', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
