# Generated by Django 5.2.5 on 2026-01-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_commercial_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'قيد الانتظار'), ('AWAITING_SETTLEMENT', 'بانتظار المقاصة'), ('COMPLETED', 'مكتملة'), ('FAILED', 'فاشلة')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'إيداع'), ('WITHDRAWAL', 'سحب'), ('TRANSFER', 'تحويل'), ('PAYMENT', 'دفع')], max_length=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(default='YER', max_length=3),
        ),
    ]
