# Generated by Django 5.2.5 on 2026-01-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_bankuser_id_alter_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='user_type',
            field=models.CharField(choices=[('CENTRAL_BANK', 'Central Bank'), ('COMMERCIAL_BANK', 'Commercial Bank'), ('UNIVERSITY', 'University'), ('CUSTOMER', 'Customer')], default='CUSTOMER', max_length=20),
        ),
    ]
