# Generated by Django 5.2.5 on 2026-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_bankuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
