# Generated by Django 5.2.5 on 2026-03-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central_bank', '0005_commercialbank_currency'),
        ('wallet', '0005_alter_bankuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from the external system (e.g. Student ID)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'commercial_bank')},
        ),
    ]
