# Generated by Django 5.2.5 on 2026-03-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_bankuser_external_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankuser',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID from the external system (e.g. Student ID)', max_length=100, null=True),
        ),
    ]
